config/routes.rb
Rails.application.routes.draw do

  resources :apptnotes

  resources :invoices

  resources :diagcodes

  resources :physicians

  resources :patients

  resources :appointments

  resources :dashboard

  root 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CISProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <nav class="tab-bar">
      <section class="left-small">
        <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>

      <section class="middle tab-bar-section">
        <h1 class="title">Dermo-pointment</h1>
      </section>

    </nav>

    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Navigation</label></li>
        <li><%= link_to "Dashboard",dashboard_index_path %>"></li>
        <li><%= link_to "Patients",patients_path %>"></li>
        <li><%= link_to "Physicians",physicians_path %>"></li>
        <li><%= link_to "Appointments",appointments_path %>"></li>
        <li><%= link_to "Appointment Notes",apptnotes_path %>"></li>
        <li><%= link_to "Diagnostic Codes",diagcodes_path %>"></li>
      </ul>
    </aside>


    <section class="main-section">
      <%= yield %>
    </section>

    <a class="exit-off-canvas"></a>

  </div>
</div>

</body>
</html>